### PR TITLE
sidecar: introduce Horizons

### PR DESCRIPTION
**Pull request by amery**
Horizons allows us to easily apply middleware to HTTP and DNS services based on the address of the clients.

### CODE REVIEW

**Comment by amery** [comment]
rebased

**Comment by amery** [comment]
made Horizon names unique, and added extra accessors.

**Comment by amery** [comment]
rebased

**Review by karasz — APPROVED** [review]
ok

**Comment by amery** [comment]
> ok

that's it? 😅

**Review by karasz — APPROVED** [review]
LGTM

**Comment by amery** [comment]
`darvaza.org/sidecar@v0.1.0` tagged

**Pull request merged**
